import React from 'react';

export default function () {
  return (
    <div className='biograph'>
     <div className='bio'>
       <h4>SHAH RUKH KHAN</h4>
       <p>hah Rukh Khan born 2 November 1965, also known by the initialism SRK, is an Indian actor, film producer, and television personality who works in Hindi films.
          Referred to in the media as the "Baadshah of Bollywood"  and "King Khan", he has appeared in more than 80 films, and earned numerous accolades, including 14 Filmfare Awards.
           The Government of India has awarded him the Padma Shri, and the Government of France has awarded him the Ordre des Arts et des Lettres and the Legion of Honour. 
           Khan has a significant following in Asia and the Indian diaspora worldwide.
           <img className="biopic" src="https://pbs.twimg.com/media/C8O-3xdUIAAOS91.jpg"/>
            In terms of audience size and income, he has been described as one of the most successful film stars in the world.
        <p>Khan began his career with appearances in several television series in the late 1980s. 
          He made his Bollywood debut in 1992 with Deewana. Early in his career, Khan was recognised for portraying villainous roles in the films Baazigar (1993), Darr (1993), and Anjaam (1994).
           He then rose to prominence after starring in a series of romantic films, including Dilwale Dulhania Le Jayenge (1995), Dil To Pagal Hai (1997), Kuch Kuch Hota Hai (1998), Mohabbatein (2000) and Kabhi Khushi Kabhie Gham... (2001). 
           Khan went on to earn critical acclaim for his portrayal of an alcoholic in Devdas (2002), a NASA scientist in Swades (2004), a hockey coach in Chak De! India (2007) and a man with Asperger syndrome in My Name Is Khan (2010). 
           His highest-grossing films include the comedies Chennai Express (2013), Happy New Year (2014), Dilwale (2015), and the crime film Raees (2017).
           Many of his films display themes of Indian national identity and connections with diaspora communities, or gender, racial, social and religious differences and grievances.</p>
        </p>
        <p>As of 2015, Khan is co-chairman of the motion picture production company Red Chillies Entertainment and its subsidiaries and is the co-owner of the Indian Premier League cricket team Kolkata Knight Riders and the Caribbean Premier League team Trinbago Knight Riders. He is a frequent television presenter and stage show performer. The media often label him as "Brand SRK" because of his many endorsement and entrepreneurship ventures. Khan's philanthropic endeavours have provided health care and disaster relief, and he was honoured with UNESCO's Pyramide con Marni award in 2011 for his support of children's education and the World Economic Forum's Crystal Award in 2018 for his leadership in championing women's and children's rights in India. He regularly features in listings of the most influential people in Indian culture, and in 2008, Newsweek named him one of their fifty most powerful people in the world.</p>
        <h4>EARLY LIFE AND FAMILY</h4>
        <p>Khan was born on 2 November 1965 into a Muslim family in New Delhi. He spent the first five years of his life in Mangalore, where his maternal grandfather, Iftikhar Ahmed, served as the chief engineer of the port in the 1960s.
           Khan's father, Meer Taj Mohammed Khan, was an Indian independence activist from Peshawar who campaigned alongside the Khudai Khidmatgar, a nonviolent resistance movement led by Abdul Ghaffar Khan (also known as Bacha Khan or the "Frontier Gandhi") that sought a united and independent India.
           Meer was a follower of Abdul Ghaffar Khan,and affiliated with the Indian National Congress. As of 2010, Khan's paternal family was still living in the Shah Wali Qataal area of Peshawar's Qissa Khwani Bazaar. Meer moved to New Delhi in 1948 after the partition of India.
           Khan's mother, Lateef Fatima, was the daughter of a senior government engineer. His parents were married in 1959. Khan described himself on Twitter as "half Hyderabadi (mother), half Pathan (father), and some Kashmiri (grandmother)". 
           According to Khan, his paternal grandfather, Meer Jan Muhammad Khan, was originally from Afghanistan.His paternal cousins in Peshawar claim that the family speaks Hindko and is originally from Kashmir, contradicting the claim that his grandfather was from Afghanistan.
        <img className="biopictwo" src="https://st1.bollywoodlife.com/wp-content/uploads/2019/05/srk-gauri-new.jpg"/>
        <p>Khan grew up in the Rajendra Nagar neighbourhood of New Delhi. His father had several business ventures including a restaurant, and the family lived a middle-class life in rented apartments. 
          Khan attended St. Columba's School in central Delhi where he excelled in his studies and in sports such as hockey and football, and received the school's highest award, the Sword of Honour. Initially Khan aspired to pursue a career in sports, however owing to a shoulder injury in his early years meant that he could no longer play. Instead, in his youth, he acted in stage plays and received praise for his imitations of Bollywood actors, of which his favourites were Dilip Kumar, Amitabh Bachchan, and Mumtaz.
          One of his childhood friends and acting partners was Amrita Singh, who became a Bollywood actress.Khan enrolled at Hansraj College (1985-88) to earn his bachelor's degree in economics, but spent much of his time at Delhi's Theatre Action Group (TAG), where he studied acting under the mentorship of theatre director Barry John. After Hansraj, he began studying for a master's degree in mass communication at Jamia Millia Islamia, but left to pursue his acting career. He also attended the National School of Drama in Delhi during his early career in Bollywood.
           His father died of cancer in 1981, and his mother died in 1991 from complications of diabetes.After the death of their parents, his older sister, Shahnaz Lalarukh (born 1960)fell into a depressed state and Khan took on the responsibility of caring for her.Shahnaz continues to live with her brother and his family in their Mumbai mansion.</p>
        <p>Although Khan was given the birth name Shahrukh Khan, he prefers his name to be written as Shah Rukh Khan, and is commonly referred to by the initialism SRK. He married Gauri Chibber, a Punjabi Hindu, in a traditional Hindu wedding ceremony on 25 October 1991, after a six-year courtship. They have a son Aryan (born 1997) and a daughter Suhana (born 2000). In 2013, they became parents of a third child, a son named AbRam, who was born through a surrogate mother.
           Both his elder children have expressed interest in entering the entertainment industry; Khan has stated that Aryan, who studied filmmaking at the USC School of Cinematic Arts in California, aspires to become a writer-director, while Suhana, who served as assistant director for Khan's film Zero (2018), is studying drama and acting at NYU's Tisch School of the Arts for higher education. Suhana made her acting debut in November 2019, in a short film titled "The Grey Part of Blue." According to Khan, while he strongly believes in Islam, he also values his wife's religion. His children follow both religions; at his home the Qur'an is situated next to the Hindu deities.</p>
        </p>
      <h4>ACTING CAREER</h4>
      <h5>1988-1992: Television and film debut</h5>
       <p>Khan's first starring role was in Lekh Tandon's television series Dil Dariya, which began shooting in 1988, but production delays led to the Raj Kumar Kapoor directed 1989 series Fauji becoming his television debut instead. In the series, which depicted a realistic look at the training of army cadets, he played the leading role of Abhimanyu Rai.[50][51] This led to further appearances in Aziz Mirza's television series Circus (1989–90) and Mani Kaul's miniseries Idiot (1992).[52] Khan also played minor parts in the serials Umeed (1989) and Wagle Ki Duniya (1988–90),[52] and in the English-language television film In Which Annie Gives It Those Ones (1989).
         His appearances in these serials led critics to compare his look and acting style with those of the film actor Dilip Kumar,but Khan was not interested in film acting at the time, thinking that he was not good enough.</p>
       <p>Khan changed his decision to act in films in April 1991,[56] citing it as a way to escape the grief of his mother's death.[57] He moved from Delhi to Mumbai to pursue a full-time career in Bollywood, and was quickly signed to four films.[56] His first offer was for Hema Malini's directorial debut Dil Aashna Hai,[29][50] and by June, he had started his first shoot.[58] His film debut was in Deewana, which was released in June 1992.[59] In it he starred alongside Divya Bharti as the second male lead behind Rishi Kapoor. Deewana became a box office hit and launched Khan's Bollywood career;[60] he earned the Filmfare Best Male Debut Award for his performance.[61] Also released in 1992 were Khan's first films as the male lead, Chamatkar, Dil Aashna Hai, and the comedy Raju Ban Gaya Gentleman, which was his first of many collaborations with the actress Juhi Chawla.[62] His initial film roles saw him play characters who displayed energy and enthusiasm. According to Arnab Ray of Daily News and Analysis, Khan brought a new kind of acting as he was "sliding down stairs on a slab of ice, cartwheeling, somersaulting, lips trembling, eyes trembling, bringing to the screen the kind of physical energy ... visceral, intense, maniacal one moment and cloyingly boyish the next.</p>  
      <h5>1993-1994: Anti-hero</h5>
       <p>Among his 1993 releases, Khan garnered the most appreciation for portraying villainous roles in two box office hits: a murderer in Baazigar, and an obsessive lover in Darr.[64] Baazigar, in which Khan played an ambiguous avenger who murders his girlfriend, shocked Indian audiences with an unexpected violation of the standard Bollywood formula.[65] In The Cambridge Companion to Modern Indian Culture, Sonal Khullar called the character "the consummate anti-hero".[66] His performance in Baazigar, which would be his first of many appearances with actress Kajol, won Khan his first Filmfare Award for Best Actor.[67] In 2003, the Encyclopaedia of Hindi Cinema stated that Khan "defied the image of the conventional hero in both these films and created his own version of the revisionist hero".[67] Darr marked the first of Khan's many collaborations with filmmaker Yash Chopra and his company Yash Raj Films. Khan's stammering and the use of the phrase "I love you, K-k-k-Kiran" were popular with audiences.[68] Malini Mannath of The Indian Express argued that he "walks away with the acting honours in yet another negative role".[69] For Darr he received a nomination for the Filmfare Award for Best Performance in a Negative Role, also known as the Best Villain Award, but lost to Paresh Rawal for Sir.[70] Also in 1993, Khan performed a nude scene with Deepa Sahi in Maya Memsaab, although parts of it were censored by the Central Board of Film Certification.[71] The ensuing controversy prompted him to eschew such scenes in future roles</p>
       <p>In 1994, Khan played a love-struck musician in Kundan Shah's comedy-drama film Kabhi Haan Kabhi Naa opposite Deepak Tijori and Suchitra Krishnamurthy, which he later professed was his favourite role. His performance earned him a Filmfare Critics Award for Best Performance, and in a retrospective review from 2004, Sukanya Verma of Rediff.com referred to it as Khan's best performance, calling him "spontaneous, vulnerable, boyish, mischievous and acting straight from the heart".[73] Also in 1994, Khan won the Filmfare Best Villain Award for his role as an obsessive lover in Anjaam, co-starring Madhuri Dixit.[67] At the time, playing antagonistic roles was considered risky to a leading man's career in mainstream Hindi cinema. Arnab Ray subsequently credited Khan for taking "insane risks" and "pushing the envelope" by choosing to play such characters, through which he established his career.[63] The director Mukul S. Anand called him "the new face of the industry" at the time.</p> 
       <h5>1995-1998: Romantic roles</h5>
       <img className="biopicthree" src="https://img.etimg.com/thumb/width-1200,height-900,imgsize-663429,resizemode-1,msid-78743159/magazines/panache/25-years-of-ddlj-bronze-statue-of-srk-kajol-to-be-unveiled-at-londons-leicester-square.jpg"/>
       <p>Khan starred in seven films in 1995, the first of which was Rakesh Roshan's melodramatic thriller Karan Arjun. Co-starring Salman Khan and Kajol, it became the second-highest-grossing film of the year in India.[74] His most significant release that year was Aditya Chopra's directorial debut, the romance Dilwale Dulhania Le Jayenge, in which he played a young Non-resident Indian (NRI) who falls in love with Kajol's character during a trip across Europe. Khan was initially reticent to portray the role of a lover, but this film is credited with establishing him as a "romantic hero".[75] Lauded by both critics and the public, it became the year's highest grossing production in India and abroad and was declared an "all time blockbuster" by Box Office India,[74][76] with a gross of over ₹1.22 billion (US$16 million) worldwide.[77] It is the longest-running film in the history of Indian cinema; it is still showing at the Maratha Mandir theatre in Mumbai after more than 1000 weeks as of early 2015.[78][79] The film won ten Filmfare Awards, including the second of Khan's Best Actor Awards.[67] The director and critic Raja Sen said, "Khan gives a fabulous performance, redefining the lover for the 1990s with great panache. He's cool and flippant, but sincere enough to appeal to the [audience]. The performance itself is, like the best in the business, played well enough to come across as effortless, as non-acting</p>
       <p>In 1996, all four of Khan's releases failed critically and commercially,[81] but the following year, his starring role opposite Aditya Pancholi and Juhi Chawla in Aziz Mirza's romantic comedy Yes Boss earned him accolades that included a Filmfare Best Actor nomination.[70] Later in 1997, he starred in Subhash Ghai's diasporic-themed social drama Pardes,[82] portraying Arjun, a musician facing a moral dilemma. India Today cites it as one of the first major Bollywood pictures to succeed in the United States.[83] Khan's final release of 1997 was the second collaboration with Yash Chopra in the popular musical romance Dil To Pagal Hai. He portrayed Rahul, a stage director caught in a love triangle between Madhuri Dixit and Karisma Kapoor. The film and his performance met with critical praise, winning Khan his third Best Actor Award at Filmfare.</p>
       <p>Khan performed the lead role in three films and made one special appearance in 1998. In his first release of the year, he played a double role opposite Juhi Chawla and Sonali Bendre in Mahesh Bhatt's action comedy Duplicate, the first of his many collaborations with Yash Johar's production company Dharma Productions. The film was not well received,[84] but India Today lauded Khan for his energetic performance.[85] The same year, Khan won critical praise for his performance as an All India Radio correspondent who develops an infatuation for a mysterious terrorist (Manisha Koirala) in Dil Se..,[86] the third instalment of Mani Ratnam's trilogy of terror films.[87][88] In his final release of the year, he portrayed a college student in Karan Johar's romance Kuch Kuch Hota Hai, in which he was involved in a love triangle along with Kajol and Rani Mukerji. The writer Anjana Motihar Chandra has referred to the picture as the blockbuster of the 1990s, a "pot-pourri of romance, comedy, and entertainment."[89] Khan won the Best Actor award at the Filmfare Awards ceremony for the second consecutive year,[67] although he and several critics believed his performance to have been overshadowed by that of Kajol.</p>
       <p>The roles in this phase of his career, and the series of romantic comedies and family dramas that followed, earned Khan widespread adulation from audiences, particularly teenagers,[91] and according to author Anupama Chopra, established him as an icon of romance in India.[92][93] He continued to have frequent professional associations with Yash Chopra, Aditya Chopra, and Karan Johar, who moulded his image and made him into a superstar.[94] Khan became a romantic leading man without ever actually kissing any of his co-stars,[92] although he broke this rule in 2012, after strong urging by Yash Chopra</p>
      <h5>1999-2003: Career challenges</h5>
       <p>Khan's only release in 1999 was Baadshah, in which he starred opposite Twinkle Khanna. Although the film underperformed at the box office,[96] it earned him a Filmfare Award nomination for Best Performance in a Comic Role, which he lost to Govinda for Haseena Maan Jaayegi.[70] Khan became a producer in 1999 in a collaboration with the actress Juhi Chawla and the director Aziz Mirza for a production company called Dreamz Unlimited.[97] The company's first production, Phir Bhi Dil Hai Hindustani (2000), starring Khan and Chawla, was a commercial failure.[98] It was released one week after Kaho Naa... Pyaar Hai, starring Hrithik Roshan, then a newcomer, who critics believed overshadowed Khan.[99] Swapna Mitter of Rediff.com spoke of Khan's predictable mannerisms, saying "Frankly, it's high time he innovated his act a little."[100] Khan did a supporting role in Kamal Haasan's Hey Ram (2000), which was made simultaneously in Tamil and Hindi. He thereby made his Tamil debut by playing the role of an archaeologist named Amjad Khan.[101] He performed free of charge as he wanted to work with Haasan.[102][103] On Khan's performance, T. Krithika Reddy of The Hindu wrote, "Shah Rukh Khan, as usual comes up with an impeccable performance</p>
       <img className="biopicfour" src="https://im.idiva.com/content/2019/Aug/iDiva_SRK_1_5d53ec0d89076.jpg"/>
       <p>In 2001, Dreamz Unlimited attempted a comeback with Khan portraying the title role in Santosh Sivan's historical epic Aśoka, a partly fictionalised account of the life of emperor Ashoka. The film was screened at the Venice Film Festival and the 2001 Toronto International Film Festival to a positive response,[104] but it performed poorly at Indian box offices.[105] As losses continued to mount for the production company,[99] Khan was forced to close srkworld.com, a company that he had started along with Dreamz Unlimited.[106] In December 2001, Khan suffered a spinal injury while performing an action sequence for a special appearance in Krishna Vamsi's Shakti: The Power.[107] He was subsequently diagnosed with a prolapsed disc, and attempted multiple alternative therapies. None of these provided a permanent solution to the injury, which caused him severe pain while shooting several of his films.[107][108] By the beginning of 2003, his condition had worsened to the point that he had to undergo anterior cervical discectomy and fusion surgery at Wellington Hospital, London.[109][110][111] Khan resumed shooting in June 2003, but he reduced his workload and the number of film roles he accepted annually.</p>
       <p>Successes during this time included Aditya Chopra's Mohabbatein (2000), and Karan Johar's family drama Kabhi Khushi Kabhie Gham... (2001),[98][112] which Khan cites as a turning point in his career.[113] Both films co-starred Amitabh Bachchan as an authoritarian figure, and presented ideological struggles between the two men.[114][115] Khan's performances in the films were met with wide public appreciation, and he was awarded his second Filmfare Critics Award for Best Actor for Mohabbatein.[70][116] Kabhi Khushi Kabhie Gham... remained the top-grossing Indian production of all time in the overseas market for the next five years</p>
       <h5>2004-2009: Resurgence</h5>
       <p>2004 was a critically and commercially successful year for Khan. He transformed Dreamz Unlimited into Red Chillies Entertainment, adding his wife Gauri as a producer.[122] In the company's first production, he starred in Farah Khan's directorial debut, the masala film Main Hoon Na. A fictionalised account of India–Pakistan relations, it was viewed by some commentators as a conscious effort to move away from the stereotypical portrayal of Pakistan as the constant villain.[123] Khan then played an Indian Air Force pilot who falls in love with a Pakistani woman (Preity Zinta) in Yash Chopra's romance film Veer-Zaara, which was screened at the 55th Berlin Film Festival to critical praise.[124] It was the highest earning film of 2004 in India, with a worldwide gross of over ₹940 million (US$12 million), and Main Hoon Na was the second-highest earner with ₹680 million (US$9.0 million)</p>
       <img className="biopicfive" src='https://www.pinkvilla.com/files/styles/ld-image/public/Priyanka-Chopra-and-Shah-Rukh-Khan-AVOID-each-other-yet-again-at-an-award-show.jpg'/>
       <p>The Times of India reported that Khan found filming the picture such an emotionally overwhelming and life-changing experience that he had still not viewed the film.[128] Derek Elley of Variety found Khan's performance "unsettling" as "a self-satisfied expatriate determined to bring Western values to poor Indian peasants",[129] but several film critics, including Jitesh Pillai, believed it to have been his finest acting to date.[130][131] He was nominated for the Filmfare Best Actor Award for all three of his 2004 releases and eventually won the award for Swades.[61][70] Filmfare later included his performance in the 2010 issue of Bollywood's "Top 80 Iconic Performances"</p>
       <p>Khan collaborated for the third time with Aditya Chopra on the romantic drama Rab Ne Bana Di Jodi (2008) opposite Anushka Sharma, at that time a newcomer. He played Surinder Sahni, a shy man with low self-esteem, whose love for his young arranged wife (Sharma) causes him to transform himself into Raj, a boisterous alter-ego. Rachel Saltz of The New York Times believed the dual role to have been "tailor-made" for Khan, giving him the opportunity to display his talents,[146] although Deep Contractor from Epilogue thought Khan displayed greater strength in the role of Surinder and weakness in the role of monologue-prone Raj.[147] In December 2008, Khan suffered a shoulder injury while filming a small role in Mudassar Aziz's Dulha Mil Gaya. He underwent extensive physiotherapy sessions at the time but the pain left him almost immobile and he had arthroscopic surgery in February 2009.[148][149] He performed a special appearance in the 2009 film Billu, playing Bollywood superstar Sahir Khan—a fictionalised version of himself, wherein he performed musical item numbers with actresses Kareena Kapoor, Priyanka Chopra, and Deepika Padukone.[150] As head of the film's production company, Red Chillies, Khan made the call to change the title of the film from Billu Barber to Billu after hairdressers across the country complained that the word "barber" was derogatory. The company covered up the offending word on billboards that had already been installed with the original title</p>
       <h5>2010-2014: My Name Is Khan and expansion to action and comedy</h5> 
       <img className="biopictwo"src='https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/SRK_Kajol_%26_Karan.jpg/220px-SRK_Kajol_%26_Karan.jpg'/>
       <p>After refusing the role that subsequently went to Anil Kapoor in Danny Boyle's Slumdog Millionaire (2008), Khan began shooting My Name Is Khan (2010), his fourth collaboration with director Karan Johar and his sixth with Kajol.[152] The film is based on a true story and set against the backdrop of perceptions of Islam after the 11 September attacks. Khan plays Rizwan Khan, a Muslim suffering from mild Asperger syndrome who sets out on a journey across America to meet the country's president, in a role that film scholar Stephen Teo sees as a "symbol of assertive rasa values" and another example of Khan representing NRI identity in global Bollywood.[153] To provide an accurate portrayal of a sufferer without disparagement, Khan spent several months researching his role by reading books, watching videos and talking to people affected by the condition.[154][155] Upon release, My Name is Khan became one of the highest grossing Bollywood films of all time outside India,[77][112] and earned Khan his eighth Filmfare Award for Best Actor,[61] equalling the record for the most wins in the category with actor Dilip Kumar.[156] Jay Wesissberg from Variety noted how Khan portrayed the Asperger's sufferer with "averted eyes, springy steps, [and] stuttered repetitions of memorized texts", believing it to have been a "standout performance sure to receive the Autism Society's gold seal of approval"</p>
       <p>The year's highest grossing Bollywood production abroad,[167][168] it was showcased at the 62nd Berlin International Film Festival.[169]</p>
       <p>Khan at an event for Chennai Express in 2013 .Khan's only release in 2012 was Yash Chopra's last picture,[170] the romantic drama Jab Tak Hai Jaan, which saw him once again in a romantic role, starring opposite Katrina Kaif and Anushka Sharma. CNN-IBN considered the overall performance by Khan to have been one of his finest to date, but believed that Khan's first screen kiss of his career with Katrina Kaif, twenty years his junior, was an awkward one.[95][171] Jab Tak Hai Jaan was a moderate financial success earning over ₹2.11 billion (US$28 million) worldwide.[172][173] The film was showcased at the 2012 Marrakech International Film Festival in Morocco, along with Kabhi Khushi Kabhie Gham..., Veer-Zaara, and Don 2.[174] At the following Zee Cine Awards, Khan performed a tribute to the late Yash Chopra along with Kaif, Sharma, and several of Chopra's other past heroines</p>
       <h5>2015-2018: Career fluctuations</h5>
        <p>Khan next appeared alongside Kajol, Varun Dhawan and Kriti Sanon in Rohit Shetty's action comedy Dilwale (2015). The film garnered mixed reviews, though it was financially profitable with a gross of ₹3.7 billion (US$49 million).[186] Namrata Joshi of The Hindu commented, "With Dilwale, Rohit Shetty goes hopelessly wrong despite much that he had at his disposal, including a power-packed cast and producer", and felt that the attempt to repackage Khan and Kajol had backfired.[187] He then took on dual parts of a superstar and his doppelgänger fan in Maneesh Sharma's action thriller Fan (2016). Peter Bradshaw of The Guardian considered the film to be "exhausting, bizarre yet watchable" and thought that Khan was aptly "creepy" as the obsessive admirer.[188] The film underperformed at the box office, and trade journalists attributed this failure to the film's non-conformity to mainstream formula.[189] Later that year, Khan portrayed the supporting part of a therapist to an aspiring cinematographer (Alia Bhatt) in Gauri Shinde's coming-of-age film Dear Zindagi.</p>
        <p>In Rahul Dholakia's action crime film Raees (2017), Khan took on the part of the titular anti-hero—a bootlegger turned mobster in 1980s Gujarat. In a typical mixed review, Pratim D. Gupta of The Telegraph thought Khan's performance to be "inconsistent, intense and power-packed at times, but often slipping out of character into his usual mix of stock mannerisms".[191] Commercially, the film was a modest success, earning about ₹3.08 billion (US$41 million) worldwide.[192][193] Khan returned to the romantic genre with the role of a tourist guide who falls in love with a traveller (Anushka Sharma) in Imtiaz Ali's Jab Harry Met Sejal (2017). In a review for Mint, Uday Bhatia criticised Khan's pairing with Sharma, 22 years his junior, writing that Khan had performed "similar gestures of love decades ago to actors his own age".[194] The film proved to be a box office flop.</p>
        <p>Khan next reunited with Sharma and Katrina Kaif in Aanand L Rai's romantic drama Zero (2018), in which he played Bauua Singh, a dwarf involved in a love triangle.[196][197] The film received mixed reviews with praise directed to Khan's performance.[198][199] Writing for Hindustan Times, Raja Sen commended his "dominating performance and tremendous energy" and Anna M. M. Vetticad of Firstpost called him an "excellent fit" for the role for allowing his "naturally energetic personality, comic timing and charm to take flight".[200][201] Commercially, it failed to do well.[202] According to a Box Office India report, Khan's stardom was impacted by his films failing to do well</p>
        <h4>OTHER WORK</h4>
        <h5>Film production and television hosting</h5>
         <p>Khan co-produced three films from 1999 to 2003 as a founding member of the partnership Dreamz Unlimited.[97] After the partnership was dissolved, he and Gauri restructured the company as Red Chillies Entertainment,[122] which includes divisions dealing with film and television production, visual effects, and advertising.[204] As of 2015, the company has produced or co-produced at least nine films.[205] Either Khan or Gauri are usually given production credits, and he has appeared in most of the films, either in the lead role, or in a guest appearance. Khan was involved in several aspects of the making of Ra.One (2011). Aside from acting, he produced the film, volunteered to write the console game script, dubbed for it, oversaw its technical development, and wrote the digital comics based on the film's characters.[206][207] Khan has occasionally done playback singing for his films. In Josh (2000) he sang the popular song "Apun Bola Tu Meri Laila". He also sang in Don (2006) and Jab Tak Hai Jaan (2012).[208] For Always Kabhi Kabhi (2011), which was produced by Red Chillies, Khan participated in the lyrical composition</p> 
         <img className="biopicfour" src="https://indiaeducationdiary.in/wp-content/uploads/2018/01/Host-Shahrukh-Khan-on-TED-Talks-India-Nayi-Soch.jpg"/>
         <p><b>Stage performances   </b> Khan is a frequent stage performer and has participated in several world tours and concerts. In 1997, he performed in Asha Bhosle's Moments in Time concert in Malaysia, and returned the following year to perform with Karisma Kapoor for the Shahrukh–Karisma: Live in Malaysia concert.[217] The same year, he participated in The Awesome Foursome world tour across the United Kingdom, Canada, and the United States along with Juhi Chawla, Akshay Kumar and Kajol, and resumed the tour in Malaysia the following year.[218][219] In 2002, Khan featured with Amitabh Bachchan, Aamir Khan, Preity Zinta, and Aishwarya Rai in the show From India With Love at Manchester's Old Trafford and London's Hyde Park; the event was attended by more than 100,000 people.[220] Khan performed alongside Rani Mukherji, Arjun Rampal and Ishaa Koppikar in a 2010 concert at the Army Stadium in Dhaka, Bangladesh.[221] The next year he joined Shahid Kapoor and Priyanka Chopra in the Friendship Concert, celebrating 150 years of India–South Africa friendship in Durban, South Africa.</p>      
         <p>Khan started an association with the "Temptations" series of concert tours by singing, dancing, and performing skits alongside Arjun Rampal, Priyanka Chopra, and other Bollywood stars in Temptations 2004, a stage show that toured 22 venues across the world.[223] The show played to 15,000 spectators at Dubai's Festival City Arena.[224] In 2008, Khan set up Temptation Reloaded, a series of concerts that toured several countries, including the Netherlands.[225] Another tour was held with Bipasha Basu and others in 2012 in Jakarta,[226] and in 2013 another series of concerts visited Auckland, Perth and Sydney.[227] In 2014, Khan performed in SLAM! The Tour in the US, Canada, and London,[228] and also hosted the Indian premiere of the live talent show, Got Talent World Stage Live</p>
         <h5>Ownership of IPL cricket team</h5>
         <img className="biopicsix" src='https://www.indicine.com/img/2012/05/SRK-celebrates-final-victory.jpg'/>
         <p>n 2008, Khan, in partnership with Juhi Chawla and her husband Jay Mehta, acquired ownership rights for the franchise representing Kolkata in the Twenty20 cricket tournament Indian Premier League (IPL) for US$75.09 million, and named the team Kolkata Knight Riders (KKR).[230] As of 2009, KKR was one of the richest teams in the IPL, with a brand value of US$42.1 million.[231] The team performed poorly on the field during the first three years.[232] Their performance improved over time, and they became the champions for the first time in 2012[232] and repeated the feat in 2014.[233] The Knight Riders hold the record for the longest winning streak by any Indian team in T20s (14)</p>
         <p>Khan performed alongside Sunidhi Chauhan and Shriya Saran at the opening ceremony of the IPL 2011 season, where they danced to Tamil songs.[235] He appeared again in 2013 alongside Katrina Kaif, Deepika Padukone and Pitbull.[236] In May 2012, the Mumbai Cricket Association (MCA) banned him from the Wankhede Stadium for five years for getting into an argument with the security staff after a match between KKR and the Mumbai Indians.[237] Khan had, however, stated that he acted only after children, including his daughter, were being "manhandled" by the security staff[237][238] and that the officials were extremely high-handed and aggressive in their behaviour,[239] he had been abused with communal indecent comment.[238] Later MCA officials had accused him of being drunk in one version of the story, hitting the guard and of completely uncharacteristically abusing a female supporter of Mumbai Indians after the match in another version of the story, which Khan had maintained it was done to support their action and for cheap publicity.[238][240][241] Wankhede guard later contradicted MCA officials' claim and said Shah Rukh Khan had not hit him.[238] Khan later apologised to his fans after his team won the final match.[242] MCA revoked the ban in 2015[243] and in 2016, Mumbai Police informed that no 'cognisable offence' was made out against Khan and they had come to the conclusion that Shah Rukh Khan was not drunk and did not use abusive language before minors at the Wankhede Stadium in 2012</p>
       </div>
       </div>   
    )
}
